baseurl = "/"
languageCode = "en-us"
title = "Casper Theme"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "Comic artist and Illustrator"
  cover = "images/cover.jpg"
  author = "Kyt Cordell"
  authorlocation = "Washington, DC"
  authorwebsite = "http://kytcordell.net"
  bio= "Kyt Cordell is an artist that primarily does illustration and comic art. She was previously a lawyer and recently transitioned to freelancing full-time."
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = ""
  twitterName = "kytcordell"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "https://twitter.com/KytCordell"
